language: node_js
node_js:
- 12
before_script:
- npm run setup
script:
- npm run lint
- npm run build
- npm test
deploy:
  - provider: npm
    email: immament@gmail.com
    api_key:
      secure: v1/Yu5ufdqJMhZ4KelIXZSSjnL+Ac1E6eUSW23kXKLAOAV8IxROwENnH6VRO93pzhCOo4pZ1LUl3mr3KKw2ZNujEl28HilGsW5qgcmNiJJ+guK0mtk2TKDUfq3z35PP2+yXJYJ/1Z7kvU7fNfGHrAr7HHu3w1ulTgqtV5eZrgJw9FHFkqDQWj1Adc0OybvsxTNbvletizTt0Bg+791WPKp+rLz1x++jmvLUTcPjJ4c5OdEu5gNa4YCfPSoEwTAtx9VyxnlJ8BMLpYZVGTASiKFWS5CSrzi+9z/jNJdhFuhYkZCKNDsKNxELlQB+BMe9ndefS7D4szElthdBxXTO1zDmBiXmsoLPKH/RFfROA8hmtSROA8ZsFsdqIq2oXrEElRzgqL23y1ra/cxT4p/mga4A4S5mKQZutI97aM6wxKjzbnSjl+zrtR1pqh0qj17Uas7Z2j6GgA9khJGHmzBt9GiwXrOSx2TAKuvqlz1H+i2lp/JSsmr/09rf6Zg6wNCwfEP+lilyipAjD9RdDDV45ZKsCCKqp9io/fYhg+gMi10s8plRjBxAaEskmAEFviRF77cI67s00+v+DXmxiw4cXX29kjoOQ9m2Y7QNcBeRFIxLIcFL/xaXFuNeGPHRcv4qU1WQ6w+QfsLSrHhuVCFd2aMJN9sWHvoY9rvwjnkepv34=
    on:
      repo: immament/ngrx-uml
      tags: true
      branch: master
    skip_cleanup: 'true'
  - provider: releases
    api_key:
      secure: tAButlHYgT1+4j8S8zhmUM6MqACOLfQJlLNO4lGiK4kN34xKsd6FwaoAka/9SQtX6kVCbH/veWOfOA1+Z+MiUIR7pkMTiPUczPRHHaMJGTwemlOId+8nO03LU2ZVOO4ESkwrtJmTbtYKlFvFEXvqQG2JA/4IIkEWJMOrqSXByLFDqzq2IJxCS166TA7OdWjT2u6jbTaR8IXjK2YK9/XqyHyup2/Uy76KvG5IWwOMQhVMk3pmcn/ZiwNR8thPL/uQDQObRFJFZnswEdb1m4EDi6/oKPSeDGOf6RYwacUSl27AMaSCVbm7IHoYbBLjBH9o4+a7/xUa42pbYrEk27pCkhUvj3/SEJ6+90XbDy5HReuYPziXk4jYy+iXRdmd8vP2WmvmXp5Nu8c+tYQRDoKYgoAGV0HJ6BSH7/wBHk7pdN7EPV1vVeLcepKTJf0N1zk4Yi27xEN8YYtKU6SlYeaLB6ZK/rQiNU1eCzeij0Tgo5NPN1hfFytPSOMLm4YViEEsOyshHDFjTnIFVYOQfHAgK+j1lQEjKz0ls6cOayOgOnndTCZOv0TIITybUfZ13CMd53B+9VeMhnZFYpOxhPnwgMovnBOHEfNvjWI6bybu58eC3PGPOC/yVGdl6MAp5lDnCw3yh6WyV8RhlyjNKWqhMEMm1TUT7jI3Suld6tAZMkk=
    on:
      repo: immament/ngrx-uml
      tags: true
      branch: master
    skip_cleanup: 'true'
