import ts from 'typescript';

export enum TypeKind {
    Unknown = ts.SyntaxKind.Unknown,
    TypeLiteral = ts.SyntaxKind.TypeLiteral,
    ExpressionWithTypeArguments = ts.SyntaxKind.ExpressionWithTypeArguments,
    TypeReference = ts.SyntaxKind.TypeReference,
    CallExpression = ts.SyntaxKind.CallExpression,
    VariableDeclaration = ts.SyntaxKind.VariableDeclaration,
    Identifier = ts.SyntaxKind.Identifier,
    PropertyAccessExpression = ts.SyntaxKind.PropertyAccessExpression,
    TypeArgument = 1001,
    Action,
    ActionReference,
    Reducer,
    NgModule,
    RegisteredReducer,
    CombineReducers,
    SymbolResolveItem,
    CreateEffect,
    OfType,
    ObservablePipe,
    StoreSelect,
    CreateSelector,
    EntityAdapter,
    ReducerOn,
    CreateFeatureSelector,
    StoreDispatch,
    StoreCreateSelector,
    EntityAdapterGetSelectors,
    ActionProps,
    RxjsOperator
}
